{
  "correctText": "17  из  них  уже  отпущены , поскольку  в   результате  проверки  подозрения  в  их  адрес  неподтвердились .",
  "errors": [
    {
      "correctReplacement": "проверки",
      "type": "case",
      "wordNumber": 9
    }
  ],
  "textWithError": "17 из них уже отпущены , поскольку в результате проверка подозрения в их адрес неподтвердились ."
}